### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by 2ndwolf** [greggman/webgl-fundamentals#102]
All "open in a separate window" links I checked are broken.

For example the first one on:
https://webglfundamentals.org/webgl/lessons/webgl-2d-drawimage.html

sends to:
https://webglfundamentals.org/webgl/lessons/..%2Fwebgl-2d-drawimage-01.html

should send to:
https://webglfundamentals.org/webgl/webgl-2d-drawimage-01.html

or more like
../webgl-2d-drawimage-01.html

**Comment by greggman** [comment]
Doh! Thank you

https://github.com/greggman/webgl-fundamentals/commit/613226fad82814ee500d221f6932dcec55a3d7aa
