### ISSUE TITLE
Texture coordinate mapping

### ISSUE THREAD

**Issue by L2L2L** [greggman/webgl-fundamentals#11]
The fundamental show how to draw a texture and to also use uv to warp a texture around a 3d object.

How would I draw from a spiritesheet in WebGL? Is it possible to to use uv texture coordinate system? 

To me, no. Cause it sound more like a technique to position and alter the image in away that it can warp around a 3d object.

**Comment by greggman** [comment]
Yes it's possible to draw from a spritesheet in WebGL. [You can see an example on this page](http://webglfundamentals.org/webgl/lessons/webgl-text-glyphs.html).

A glyph texture atlas is the same as a sprite texture atlas just change the letters to whatever you want your sprites to be.
