### ISSUE TITLE
Tick mark wrong in texture sample

### ISSUE THREAD

**Issue by PrincessGod** [greggman/webgl-fundamentals#116]
[In this sample](https://webglfundamentals.org/webgl/webgl-3d-textures-repeat-clamp.html),
use this code in render part
``` javascript
       // Compute the projection matrix
132    var projectionMatrix =
133        m4.orthographic(0, gl.canvas.clientWidth, gl.canvas.clientHeight, 0, -1, 1);
```
and the `m4.orthographic()` set  0 -> `gl.canvas.clientHeight` form top to bottom
``` javascript
...
    function orthographic(left, right, bottom, top, near, far, dst) {
...
```
but set 0 -> positive (-1, 4) from bottom to top for tick marks , 
maybe it have to be (4, -1) from bottom to top.
I founded this when check both direction to `CLAMP_TO_EDGE`.

**Comment by greggman** [comment]
Doh! Fixed

https://github.com/greggman/webgl-fundamentals/commit/5815d73701ec39c56bc95461a0808df76445e3c3
