### ISSUE TITLE
shader att/color blend 

### ISSUE THREAD

**Issue by dongbo12300** [greggman/webgl-fundamentals#169]
1.if the shader have vertexcolor attribute,but the mesh data not have vertexcolor  data, can we give the vertex color of shader a default value ,such as white color?

2.After src color blend with dst color,we get a new color,whether it  will be clamp 0-1? maybe the new color will be use to blend with other,l confused with the blend result.

**Comment by greggman** [comment]
I will be happy to answer your questions but not here. These issues are for additions and bugs with the site itself. Please ask in the comments OR ask on stackoverflow.com.  I monitor both and will be happy to answer there.
