### ISSUE TITLE
WebGL auto clear color?

### ISSUE THREAD

**Issue by PrincessGod** [greggman/webgl-fundamentals#174]
Hi, @greggman .

I found in [this sample](https://jsfiddle.net/6stfxtgq/), when comment these lines

```javascript
72    //webglUtils.resizeCanvasToDisplaySize(gl.canvas);
73
74    // Tell WebGL how to convert from clip space to pixels
75    //gl.viewport(0, 0, gl.canvas.width, gl.canvas.height);
76
77    // Clear the canvas.
78    //gl.clear(gl.COLOR_BUFFER_BIT);
```

`drawScene()` still clear history draw, do you know the reason? 

Thank you.

**Comment by greggman** [comment]
Sorry I guess I never covered that.

Yes, WebGL by default clears the canvas by default after the canvas has been compositied.

If you want it not to clear the canvas you need to add `preserveDrawingBuffer: true` when creating the context as in

    const gl = someCanvas.getContext("webgl", {preserveDrawingBuffer: true});

**Comment by PrincessGod** [comment]
Really helpful, thank you very mach!
