### ISSUE TITLE
Share these tutorials in a china knowledge share site?

### ISSUE THREAD

**Issue by PrincessGod** [greggman/webgl-fundamentals#190]
Hi greg :)

Your tutorials is perfect resources for newer who want learn WebGL from basic, really appreciate.  

But a lot of china developers not know these tutorials, some of them not good at English, do not known how to learn WebGL from begining. 

So I am thinking share the Simplify Chinese version of these tutorials in a china knowledge share site [ZhiHu](https://www.zhihu.com/), is that legal to you? If not, i will not do that.

Thanks, BW.

**Comment by greggman** [comment]
yes of course you can share them in China whereever you'd like me They are
MIT licenced

**Comment by PrincessGod** [comment]
Thanks! 👍
