### ISSUE TITLE
Chapter webgl-3d-camera, Vector3 cross product is inversed?

### ISSUE THREAD

**Issue by jimtang** [greggman/webgl-fundamentals#191]
The annotation under figure-6 is:

> zAxis cross up = xAxis

but the code belowing is :
`var xAxis = cross(up, zAxis);
var yAxis = cross(zAxis, xAxis);`

According the ‘The left hand rule applied to Cross(a, b).’ rule, I think the code is right, and the annotation is wrong, please check it!

**Comment by greggman** [comment]
You mean you think it should say

    up cross zAxis = xAxis

?

**Comment by jimtang** [comment]
Yeah, that's correct.

**Comment by jimtang** [comment]
BTW, I suggest a wiki link about Vector3 cross product should be listed after this chapter, in case some readers don't get that how these 3 axis are produced.

At last, thanks for the great tutorials, it helps me a lot!

**Comment by greggman** [comment]
https://github.com/greggman/webgl-fundamentals/commit/1206ae62048e10f9d66e5da319bb2cf66c5b6121
