### ISSUE TITLE
Wrong link address

### ISSUE THREAD

**Issue by dyarosla** [greggman/webgl-fundamentals#22]
On
http://webglfundamentals.org/webgl/lessons/webgl-image-processing.html

The final link under the
**What's with the a_, u_, and v_ prefixes in from of variables in GLSL?** box that is labeled 
See **How it works** for more details
links to 404 page:
http://webglfundamentals.org/webgl/lessons/webgl-how-to-works.html

but should link to:
http://webglfundamentals.org/webgl/lessons/webgl-how-it-works.html

**Comment by greggman** [comment]
thanks! [fixed it](https://github.com/greggman/webgl-fundamentals/commit/4935b58ceffd486383be48475fa89fedbff33766). 

You might have to clear your cache or at least refresh to is it fixed.
