### ISSUE TITLE
Problem with the image of skinning

### ISSUE THREAD

**Issue by jiebai** [greggman/webgl-fundamentals#231]
hi，maybe the image https://webglfundamentals.org/webgl/lessons/resources/skinned-mesh.svg is wrong，the number of vertices  is not matching with the explanation after the image

**Comment by greggman** [comment]
fixed?

**Comment by jiebai** [comment]
Maybe it should be
![1553678431788](https://user-images.githubusercontent.com/5625498/55065011-00406180-50b6-11e9-985f-1907a991b388.jpg)

**Comment by greggman** [comment]
Doh! Wow, that's some serious brainfart right there 😅 Fixed?

**Comment by jiebai** [comment]
yes，already fixed
