### ISSUE TITLE
In 《WebGL 3D Perspective》,Why is the effect the same?

### ISSUE THREAD

**Issue by woleicom** [greggman/webgl-fundamentals#241]
In 《WebGL 3D Perspective》，WebGL automatically divides by W useful
```
 // Adjust the z to divide by
  float zToDivideBy = 1.0 + position.z * u_fudgeFactor;
 
  // Divide x and y by z.
  gl_Position = vec4(position.xy / zToDivideBy, position.zw);
```
and
```
// Divide x, y and z by zToDivideBy
  gl_Position = vec4(position.xyz, zToDivideBy);
```

to ( f = z * fugdeFactor + 1) :

```
[x/f , y/f , z ,  w]      and    [x/f , y/f , z/f , f/ f]
```
```
x/f , y/f ,  z ,   w(1)
 |       |     |       |
x/f , y/f , z/f    f/f(1)

```
W defaults to 1, but Z-bit operations are inconsistent. Why is the effect the same?

**Comment by greggman** [comment]
gl_Position.z doesn't effect the translation of 3D points to 2D points, it only effects clipping and the depth buffer. But we're not using the depth buffer at that point in the article.

**Comment by woleicom** [comment]
> gl_Position.z doesn't effect the translation of 3D points to 2D points, it only effects clipping and the depth buffer. But we're not using the depth buffer at that point in the article.

thank you

**Comment by greggman** [comment]
Actually I take that back. We are using the depth buffer. But still, `gl_Position.z` doesn't effect the translation to 2D. It only affects the depth buffer and clipping

      ndcX =  gl_Position.x / gl_Position.w;
      ndcY =  gl_Position.y / gl_Position.w;
      canvasPixelX = (ndxX * 0.5 + 0.5) * viewport.width + viewport.x;
      canvasPixelY = (ndxY * 0.5 + 0.5) * viewport.height + viewport.y;
