### ISSUE TITLE
Scaled Normals Diagram

### ISSUE THREAD

**Issue by stefnotch** [greggman/webgl-fundamentals#26]
This line:
```
  window.addEventListener('mousedown', function(e) {
      event.preventDefault();
  });
```
throws an error (event is not defined) since the name is "e" instead of "event".

The same issue is present here:
```
  function toggleNormals(e) {
    event.preventDefault();
    showNormals = !showNormals;
    render();
  }
```

Also, thanks for the amazing tutorial!

**Comment by greggman** [comment]
DOH!  Thank you for telling me. I think it's fixed
