### ISSUE TITLE
Tiny mistake in the code

### ISSUE THREAD

**Issue by stefnotch** [greggman/webgl-fundamentals#27]
In http://webglfundamentals.org/webgl/lessons/webgl-3d-textures.html this is part of the code:

```image.src = "resources/f-texture.png";
image.addEventLisenter('load', function() {```

It should be ```addEventListener``` instead of `addEventLisenter`

**Comment by greggman** [comment]
Thanks! [Fixed](https://github.com/greggman/webgl-fundamentals/commit/edf4823cd36c461cd56be928cbfa71cd7c60957b)
