### ISSUE TITLE
Frames with examples are not working in other languages

### ISSUE THREAD

**Issue by kolosov-sergey** [greggman/webgl-fundamentals#38]
It seems that with the new `editor.js` examples are not working anymore in fr and pl translations. Though the link is correct and you can open example in separate window. 

Check folllowing pages:
https://webglfundamentals.org/webgl/lessons/webgl-fundamentals.html
https://webglfundamentals.org/webgl/lessons/fr/webgl-fundamentals.html
https://webglfundamentals.org/webgl/lessons/pl/webgl-fundamentals.html

In fr and pl you see just loading indicator instead of working example.

**Comment by greggman** [comment]
Thanks for noticing. I thought I checked that. Will fix ASAP

**Comment by greggman** [comment]
It should work now. You might need to refresh/clear cache

**Comment by kolosov-sergey** [comment]
Yep, it is working now, thank you
