### ISSUE TITLE
Why applying zToDivideBy as W works on Z axis?

### ISSUE THREAD

**Issue by trusktr** [greggman/webgl-fundamentals#68]
When we divided `position.xy/zToDivideBy`, we didnt' divide the z axis. But when we apply zToDivideBy as w, then it also divides the z value.

So the first one is

```glsl
gl_Position = vec4(position.xy/zToDivideBy, position.zw)
```

but when we apply zToDivideBy to w,

```glsl
gl_Position = vec4(position.xyz, zToDivideBy)
```

it is the same as

```glsl
gl_Position = vec4(position.xyz/zToDivideBy, position.w)
```

Which is slightly different that the first one (we're also dividing the z value by zToDivideBy).

I just want to make sure, but I think it doesn't matter what we divide z by because it is the same in the orthogonal sense, and we already figured out how to adjust x and y based on the original z value, so any new z value doesn't really matter (and depth order will be still be the same)?

**Comment by greggman** [comment]
Z still needs to be between -1 and 1 after being divided by W or it will be clipped.

Also W is important for perspective correct interpolation of varyings but I'm not sure how to explain that part yet.

**Comment by trusktr** [comment]
> Z still needs to be between -1 and 1 after being divided by W or it will be clipped.

So that's really the only thing that will alter the graphic. So dividing Z by Z actually makes it smaller magnitude and less likely.

> Maybe I can insert one more step showing that if you don't divide by W you won't get correct varyings [in the texture lesson].

Cool, sounds like something good to know. About those varyings, when we used them to pass colors from the vert shader to the frag shader,  we had the same color for every three vertices. Does it only matter what color we pass from every third shader? f.e., I was thinking it would execute 3 vertex shaders then finally the frag shaders for the triangle, so then the color would be passed from the third of the three initial vert shaders?
