### ISSUE TITLE
Default value for UNPACK_PREMULTIPLY_ALPHA_WEBGL

### ISSUE THREAD

**Issue by floyd1982** [greggman/webgl-fundamentals#7]
Hi,

i read this article:
http://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html

And it helped me A LOT, thank you very much!

But I think there is an mistake on it. If you look here:
https://www.khronos.org/registry/webgl/specs/1.0/#PIXEL_STORAGE_PARAMETERS

It seems the default value for UNPACK_PREMULTIPLY_ALPHA_WEBGL is false, not true like you stated, if I understood you corretly.

Kind gerads,
Stefan

**Comment by greggman** [comment]
Doh! Thanks. Fixed

https://github.com/greggman/webgl-fundamentals/commit/bd64b4ae2ebd6e4bd70d00dd5907d34e9cfcfb18
