### ISSUE TITLE
Should I move to webgl2fundamentals?

### ISSUE THREAD

**Issue by trusktr** [greggman/webgl-fundamentals#71]
I was reading your blog, and it seems like webgl2fundamentals is basically the same thing, but better. Maybe I should just stop where I am and restart on webgl2, rewriting my code until I catch up to where I was in webgl1. What's your recommendation?

Well, webgl2 isn't in Edge or Safari yet. Hmmm.

**Comment by stefnotch** [comment]
WebGL 2 is pretty similar to WebGL. (As far as I know, the main differences are: a slightly different shader syntax and a few more cool functions)

So, if you decide to read webgl2fundamentals, the vast majority of your code should stay the same. :)

**Comment by greggman** [comment]
It's up to you. WebGL2 isn't supported everywhere yet. It will probably be at least 12-18 months until it gets close to WebGL's level of support (if that).

The one thing I would consider taking from WebGL2 and the WebGL2 lessons is that using Vertex Array Objects should probably be the recommended way even in WebGL1. Vertex Array Objects are supported everywhere except in Edge/IE11 but there's [a polyfill](https://github.com/greggman/oes-vertex-array-object-polyfill) if you care about Edge/IE11
