### ISSUE TITLE
How do you compute the position of the F when using lookAt?

### ISSUE THREAD

**Issue by trusktr** [greggman/webgl-fundamentals#74]
The guide says

```
  // Compute the position of the first F
  var fPosition = [radius, 0, 0];
```

but doesn't explain where radius comes from, or how we create `fPosition`.

(I mean, without looking at the code)

**Comment by trusktr** [comment]
Ah, I see, we'd normally just yank the object position out of its matrix, but in this case we know the F isn't moving anywhere inside its world, we're only moving the camera.

I can take it from here. :D

**Comment by trusktr** [comment]
Crap, but if we are calculating the object's matrix _after_ we've applied the camera..... then how to we get the position of an object that we are animating so we can give it to the camera before we calculate the camera?

I see that we can probably use the previous frame's object's position, but the camera will be one frame behind then.

Basically, we need the object's world-position. So f.e. if I am drawing stuff like this:

```
    window.zpos = 0
    ~function draw(time) {
        tween.update(time)

        gl.clearColor(0, 0, 0, 1)
        gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT) // why do we need to do this?

        zRotationMatrix = m4.zRotation(angle.theta)
        yRotationMatrix = m4.yRotation(angle.theta)

        let matrix = m4.identity
        matrix = m4.multiply(matrix, projectionMatrix)

        cameraAngle++
        let cameraMatrix  = m4.identity
        cameraMatrix      = m4.multiply(cameraMatrix, m4.yRotation(cameraAngle))
        cameraMatrix      = m4.multiply(cameraMatrix, m4.translation(0, 0, camRadius * 1.5))
        const viewMatrix  = m4.inverse(cameraMatrix)

        // viewProjectionMatrix
        matrix = m4.multiply(matrix, viewMatrix)

        // Node (root object)
        //
        // place everything where we want it near the center. the new
        // projectionMatrix puts the X andY origin in the center of the screen,
        // and Z is 0 at the screen and goes  negative away from the screen.
        matrix = m4.multiply(matrix, m4.translation(0, 0, zpos))

        // Node > Node
        //
        // matrix math is written in the opposite direction now, so that we can
        // apply the previous projection matrix only once, before all
        // drawArrays calls. For each matrix applied, think of them as happening
        // from the lastone to the first one.
        matrix = m4.multiply(matrix, translationMatrix)
        matrix = m4.multiply(matrix, zRotationMatrix)
        matrix = m4.multiply(matrix, yRotationMatrix)
        matrix = m4.multiply(matrix, scaleMatrix)
        matrix = m4.multiply(matrix, originMatrix)
        gl.uniformMatrix4fv(matrixLocation, false, matrix)

        gl.drawArrays(gl.TRIANGLES, offset, count)

        for (let i = 0; i < 5; ++i) {
            // Node > Node > Node
            matrix = m4.multiply(matrix, translationMatrix)
            matrix = m4.multiply(matrix, zRotationMatrix)
            matrix = m4.multiply(matrix, yRotationMatrix)
            matrix = m4.multiply(matrix, scaleMatrix)
            matrix = m4.multiply(matrix, originMatrix)
            gl.uniformMatrix4fv(matrixLocation, false, matrix)

            gl.drawArrays(gl.TRIANGLES, offset, count)
        }

        requestAnimationFrame(draw)
    }()
```

then if I want to add the `lookAt` stuff, I will calculate the camera's matrix before I've calculated the object's matrix.

Maybe it would be good to do the calculations in the [opposite order](https://github.com/greggman/webgl-fundamentals/issues/62)? (but then I'd need to calculate the final world matrix of each item from the leaf to root each time rather than compounded, which would take more CPU).

How do you recommend animating the object and getting position _before_ calculating the camera matrix?

**Comment by greggman** [comment]
There's an infinite number of ways to do this and it's really up to you as a programmer to decide. It's like you`re asking me `x = a * b * c *  d * e  * f`,  how do I isolate the `a * b * c` part from the `d * e * f` part?

How about

     abc = a * b * c
     def = d * e * f
     x = abc * def

In WebGL's case it's

     worldViewProjection = projection * view * world;

In your example above `world` is

      translationMatrix * zRotationMatrix * yRotationMatrix * scaleMatrix * originMatrix

So

     viewProjection = projection * view
     world =  translationMatrix * zRotationMatrix * yRotationMatrix * scaleMatrix * originMatrix

     worldViewProjection = viewProjection * world

It's also common to pass those matrices into the shader and do the math in the shader

      attribute vec4 position;
      uniform mat4 world;
      uniform mat4 view;
      uniform mat4 projection;
  
      void main() {
          gl_Position = projection * view * world * position;
      }

**Comment by trusktr** [comment]
Interesting. Yep, I have a scene graph here: http://github.com/trusktr/infamous, that just renders to CSS transforms at the moment. But now that I'm learning WebGL, I'm imagining basically what the HTML/CSS engine does with the matrices because that's what we're doing here now. I'm thinking that I'll just traverse the tree and calculate world transforms starting from the root, and cache them (which I'm guessing the CSS engine probably does with nested DOM).

But I guess the scene graph lesson (etc) is coming up so that will probably help me think about how to organize. Thanks!
