### ISSUE TITLE
Why normalize normal vectors inside fragment shader?

### ISSUE THREAD

**Issue by trusktr** [greggman/webgl-fundamentals#77]
For example, if we have three vertices each with normal `0,1,0`, then when the normals are interpolated between the vertices for each fragment, I don't see why we need to normalize.

How is it interpolating from  `0,1,0` to `0,1,0` will yield anything other than `0,1,0` if the values (normals) are exactly the same?

If we don't normalize, f.e.

```glsl
vec3 normal = normalize(v_normal);
```

then what will the values look like across the fragments? Can you explain what to expect if we don't normalize?

**Comment by trusktr** [comment]
I think it has to do with what you said in the point light lesson:

> Now in the fragment shader we need to normalize the surface to light vector since it's a not a unit vector. Note that we could normalize in the vertex shader but because it's a varying it will be linear interpolated between our positions and so would not be a complete unit vector

but I'm not completely understanding of it yet. In the case of surface-to-light vectors, I think I can understand since the numbers vary from vertex to vertex that the interpolation will yield values in between, and we normalize them in the fragments.

But with normals, they are the same value from vertex to vertex so I would think that after they are interpolated that they are the same value, so they don't need to be normalized. I will play with it after finishing the point light tutorial...

**Comment by greggman** [comment]
Because not every object has flat surfaces.

**Comment by trusktr** [comment]
Oh, so you mean for something like a sphere, the normals would be pointing away from the center of the sphere, not necessarily normal to the surface of the sphere's triangles, and that way it can make smoother transitions in the colors (f.e. shadows, etc)?

So if the normals were always perpendicular to the triangles, then we'd always see sharp triangles? 

Cool. Haven't gotten that far yet, but cool.

**Comment by trusktr** [comment]
But in the specular part of the point light lesson, we have

```glsl
// vertex shader
  v_surfaceToView = normalize(u_viewWorldPosition - surfaceWorldPosition);
```

and 

```glsl
// fragment shader
  vec3 surfaceToViewDirection = normalize(v_surfaceToView);
```

Do we need to normalize in both vert and frag shader? Or can we just normalize in the frag shader?
