### ISSUE TITLE
Ui rotation can not capture mouse 

### ISSUE THREAD

**Issue by PrincessGod** [greggman/webgl-fundamentals#93]
In [this example](https://webglfundamentals.org/webgl/webgl-2d-geometry-rotation.html), `div#rotation`get `pointer-event: none;` attribute from “Webgl-tutorials.css".So can't drag circle to rotation.
Here is the screenshot.
![2017-07-19_00-01-36](https://user-images.githubusercontent.com/20556748/28327452-0d66f8dc-6c16-11e7-9a9c-43809eb0bf61.png)

**Comment by greggman** [comment]
Sorry about that. Fixed: https://github.com/greggman/webgl-fundamentals/commit/866445a130bffd13830f9e16e68025eeda98b911
