### ISSUE TITLE
Possible typo "renderering"?

### ISSUE THREAD

**Issue by L1Q** [greggman/webgl-fundamentals#98]
On [webgl-fundamentals](https://webglfundamentals.org/webgl/lessons/webgl-fundamentals.html) page right at the end of "WebGL Hello World" section it ways 

> The code below this point is _renderering_ code

It's a typo I assume and it should say "rendering"

**Comment by PrincessGod** [comment]
Yes, that‘s a typo, and I have fix it in 62f1dd1 . Thank you !
